### ISSUE TITLE
Code to communicate with client

### ISSUE THREAD

**Issue by SylviaCHS** [SylviaCHS/BME547_Final_Project#25]

**Comment by tiffanylin43** [comment]
@SylviaCHS Is there anything that I can help in this part? I guess there should be some image processing functions I wrote that would be called when displaying the histogram and image size.

**Comment by SylviaCHS** [comment]
@tiffanylin43 I am still working on Loading image to the GUI and haven't started the display histogram and image size. It would be nice if you can work on it! I left 2 image spots for the two histograms.

**Comment by KimberlyLennox** [comment]
@SylviaCHS 
Hi Sylvia,

I've added the last part of the server code: /api/download_image.

This will retrieve an image in any filetype.  I'm pretty sure that this is the last function necessary on the server side. If I'm missing something, please let me know.

**Comment by SylviaCHS** [comment]
@kkl18 Hi Kim, pillow is able to save the nparray image we get from server to most of the image datatype. I wrote code to do that in the client side. Now the GUI is able to display and output JPEG, TIFF, and PNG, as well as zip multiple files to download. ( In branch 'hc239/client_multiple_files')

I think it is easier to process it on the client side. Could we do the image type conversion in the client side? @dward2 

Thanks,
Sylvia

**Comment by KimberlyLennox** [comment]
@SylviaCHS 

Go with whichever method is easier for you, provided it fits the project description. The server code is there if you need it.

**Comment by dward2** [comment]
@SylviaCHS I think as long as you are doing only type conversion (i.e., JPG to TIFF), it is okay to do that on the client side.
