### ISSUE TITLE
Do histogram-related stuff seperately on R,G,B channel and validate the data.

### ISSUE THREAD

**Issue by tiffanylin43** [SylviaCHS/BME547_Final_Project#26]
@kkl18 Hi, Kim! I'll update here once I've got the new codes working.

**Comment by tiffanylin43** [comment]
@kkl18 Hi, Kim! I've uploaded the new codes doing histogram related operation separately on R, G, B channels. Please check if the new codes resolve the histogram related problem showing up ealier.

**Comment by KimberlyLennox** [comment]
@tiffanylin43 Can you check the contrast stretching and log compression as it's being run through the server code? I can't see a difference in my processed images.

**Comment by tiffanylin43** [comment]
@kkl18 Hi, Kim! I've checked these two functions and I guess both of them are working. For the log compression, I've used the astronaut and cameraman images in skimage database to test. From the comparison in pixel values before and after the operation, it's obvious that the function definitely worked. I've also used imshow to show the image, but didn't see many differences, either. I think the top half of the image has become lighter if I look very closely. You may check that, too.

**Comment by tiffanylin43** [comment]
@kkl18 For the contrast stretch, I thinks it's still a problem with the image used. The function is supposed to stretch the pixel value to the full length of range according to it's bits. Say, we have a 8-bit image, so the goal is to stretch the image in order to make sure that it take use of the full range, which is [0, 255]. That is, if the image already have pixel values of 0 and 255, it already covers the full range. So the function actually does nothing in case like this.

**Comment by tiffanylin43** [comment]
@kkl18 So for these two functions, I guess the differences between before and after the operation largely depends on the image input itself. These two operations are like contrast enhancement operations, so if the image is not in low contrast or with other major contrast issues, the differences won't be too visible, I guess.

**Comment by tiffanylin43** [comment]
@kkl18 Accidentlly closed this issue when replying just now. I've reopened it, let me know if there's any other issues with the image processing part and what else I may help.
