### ISSUE TITLE
Python crashes on Mac OS 

### ISSUE THREAD

**Issue by SylviaCHS** [SylviaCHS/BME547_Final_Project#63]
Hello Dr. Ward @dward2 ,

After adding the display histogram feature, my server code crashes every time I tried to communicate with it on my Macbook, but the code runs fine on a Windows laptop. Any ideas on how should I deal with this? Thank you!

I've attached the errors I got here:
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2019 17:26:15] "POST /api/new_user HTTP/1.1" 200 -
2019-04-28 17:26:40.077 Python[2515:97963] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff2c8c2ccc -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 386
	1   AppKit                              0x00007fff2c8c007c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
	2   AppKit                              0x00007fff2c8bfaa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   _macosx.cpython-37m-darwin.so       0x00000001197a14c0 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 80
	4   _macosx.cpython-37m-darwin.so       0x00000001197a4a17 FigureManager_init + 327
	5   Python                              0x00000001039320bc wrap_init + 12
	6   Python                              0x00000001038e9e09 wrapperdescr_call + 121
	7   Python                              0x00000001038e2ae1 _PyObject_FastCallKeywords + 433
	8   Python                              0x00000001039a16d4 call_function + 420
	9   Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	10  Python                              0x00000001038e3100 function_code_fastcall + 128
	11  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	12  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	13  Python                              0x0000000103932001 slot_tp_init + 145
	14  Python                              0x000000010392d959 type_call + 297
	15  Python                              0x00000001038e2ae1 _PyObject_FastCallKeywords + 433
	16  Python                              0x00000001039a16d4 call_function + 420
	17  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	18  Python                              0x00000001038e3100 function_code_fastcall + 128
	19  Python                              0x00000001039a1812 call_function + 738
	20  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	21  Python                              0x00000001039a2336 _PyEval_EvalCodeWithName + 2422
	22  Python                              0x00000001038e286b _PyFunction_FastCallDict + 523
	23  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	24  Python                              0x00000001038e2df7 PyObject_Call + 135
	25  Python                              0x000000010399eae7 _PyEval_EvalFrameDefault + 25975
	26  Python                              0x00000001039a2336 _PyEval_EvalCodeWithName + 2422
	27  Python                              0x00000001038e2c91 _PyFunction_FastCallKeywords + 257
	28  Python                              0x00000001039a1812 call_function + 738
	29  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	30  Python                              0x00000001038e3100 function_code_fastcall + 128
	31  Python                              0x00000001039a1812 call_function + 738
	32  Python                              0x000000010399e877 _PyEval_EvalFrameDefault + 25351
	33  Python                              0x00000001038e3100 function_code_fastcall + 128
	34  Python                              0x00000001039a1812 call_function + 738
	35  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	36  Python                              0x00000001038e3100 function_code_fastcall + 128
	37  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	38  Python                              0x000000010399eae7 _PyEval_EvalFrameDefault + 25975
	39  Python                              0x00000001038e3100 function_code_fastcall + 128
	40  Python                              0x00000001039a1812 call_function + 738
	41  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	42  Python                              0x00000001038e3100 function_code_fastcall + 128
	43  Python                              0x00000001039a1812 call_function + 738
	44  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	45  Python                              0x00000001038e3100 function_code_fastcall + 128
	46  Python                              0x00000001039a1812 call_function + 738
	47  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	48  Python                              0x00000001038e3100 function_code_fastcall + 128
	49  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	50  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	51  Python                              0x0000000103930bc6 slot_tp_call + 150
	52  Python                              0x00000001038e2ae1 _PyObject_FastCallKeywords + 433
	53  Python                              0x00000001039a16d4 call_function + 420
	54  Python                              0x000000010399e877 _PyEval_EvalFrameDefault + 25351
	55  Python                              0x00000001039a2336 _PyEval_EvalCodeWithName + 2422
	56  Python                              0x00000001038e2c91 _PyFunction_FastCallKeywords + 257
	57  Python                              0x00000001039a1812 call_function + 738
	58  Python                              0x000000010399e877 _PyEval_EvalFrameDefault + 25351
	59  Python                              0x00000001039a2336 _PyEval_EvalCodeWithName + 2422
	60  Python                              0x00000001038e2c91 _PyFunction_FastCallKeywords + 257
	61  Python                              0x00000001039a1812 call_function + 738
	62  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	63  Python                              0x00000001038e3100 function_code_fastcall + 128
	64  Python                              0x00000001039a1812 call_function + 738
	65  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	66  Python                              0x00000001038e3100 function_code_fastcall + 128
	67  Python                              0x00000001039a1812 call_function + 738
	68  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	69  Python                              0x00000001038e3100 function_code_fastcall + 128
	70  Python                              0x00000001039a1812 call_function + 738
	71  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	72  Python                              0x00000001038e3100 function_code_fastcall + 128
	73  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	74  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	75  Python                              0x0000000103932001 slot_tp_init + 145
	76  Python                              0x000000010392d959 type_call + 297
	77  Python                              0x00000001038e2ae1 _PyObject_FastCallKeywords + 433
	78  Python                              0x00000001039a16d4 call_function + 420
	79  Python                              0x000000010399e7d6 _PyEval_EvalFrameDefault + 25190
	80  Python                              0x00000001038e3100 function_code_fastcall + 128
	81  Python                              0x00000001039a1812 call_function + 738
	82  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	83  Python                              0x00000001038e3100 function_code_fastcall + 128
	84  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	85  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	86  Python                              0x00000001038e2df7 PyObject_Call + 135
	87  Python                              0x000000010399eae7 _PyEval_EvalFrameDefault + 25975
	88  Python                              0x00000001038e3100 function_code_fastcall + 128
	89  Python                              0x00000001039a1812 call_function + 738
	90  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	91  Python                              0x00000001038e3100 function_code_fastcall + 128
	92  Python                              0x00000001039a1812 call_function + 738
	93  Python                              0x000000010399e7bc _PyEval_EvalFrameDefault + 25164
	94  Python                              0x00000001038e3100 function_code_fastcall + 128
	95  Python                              0x00000001038e26f4 _PyFunction_FastCallDict + 148
	96  Python                              0x00000001038e3b3f _PyObject_Call_Prepend + 143
	97  Python                              0x00000001038e2df7 PyObject_Call + 135
	98  Python                              0x0000000103a29bd7 t_bootstrap + 71
	99  Python                              0x00000001039e0819 pythread_wrapper + 25
	100 libsystem_pthread.dylib             0x00007fff5c731305 _pthread_body + 126
	101 libsystem_pthread.dylib             0x00007fff5c73426f _pthread_start + 70
	102 libsystem_pthread.dylib             0x00007fff5c730415 thread_start + 13
)
127.0.0.1 - - [28/Apr/2019 17:28:13] "POST /api/new_image HTTP/1.1" 200 -
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.20.108/AppKit.subproj/NSView.m, line 14143.
Illegal instruction: 4

**Comment by dward2** [comment]
Presumably, the display histogram function was added to your GUI client, correct?  If so, the only way that could be making the server crash is if the GUI client makes some sort of call to the server while executing the "display histogram function."  What call is it making?

**Comment by SylviaCHS** [comment]
The display histogram is added to my GUI client. However, when the error occurs, I hasn't call my newly added function yet, it was just trying to upload the new image I chose. It is calling the "POST /api/new_image", which will upload a new image to server.

**Comment by dward2** [comment]
Then, try this:  comment out all of your new code for displaying the histogram, and see if it goes back to working.  If it still doesn't work, that will tell you that it has nothing to do with the new code you added, but is broken in some other fashion.

**Comment by dward2** [comment]
Let me ask another question.  When you added this display historgram functionality, did you need to import `matplotlib` in some fashion with the new code?

**Comment by SylviaCHS** [comment]
@dward2 sorry about the late reply. Yes, we did use matplotlib, and I think Mac really doesn't like it. 

I add plt.close() every time it opens a plot. Now it it running okay although I am still getting the warnings. 

Thanks!
Sylvia

**Comment by dward2** [comment]
If it is running correctly, ignore the warnings.  Good job determining that closing the plots helps.
