### ISSUE TITLE
Unit tests 

### ISSUE THREAD

**Issue by tiffanylin43** [SylviaCHS/BME547_Final_Project#64]
@dward2 
Hi, Dr.Ward! I'm writing unit tests for our latest codes. But I'm not sure if the tests are needed or how to do the tests for certain functions.

For 'client.py', most of the functions are used to communicate with the server, which we don't have to test, right? For the left 2 functions called 'read_file_as_b64(image_path)' and 'save_b64_image(base64_string)',  I'm not sure if the tests are need. If so, how should they be tested? I think they are basically doing data conversion, but not sure how to test if the function works.

For 'client_inline.py', there is another function called 'download_b64_image(base64_string, filename)', do I need to test it?

**Comment by tiffanylin43** [comment]
@dward2 Also, there are a lot of functions doing data conversion or data validation but requires communication with MongoDB, are tests needed for them? If so, how can we test them?

**Comment by dward2** [comment]
Those data tests or conversions should be done in a different function that can be tested separate from MongoDB
________________________________

**Comment by KimberlyLennox** [comment]
@dward2 OK, we'll be sure to include those tests. The other question that we had was about FileIO type functions. These are functions that convert data into a savable format (no processing, just saving). Do those need to be tested?

**Comment by tiffanylin43** [comment]
All the unit tests should have been added.
